// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-BXgeYMyKW6OTiuU4nc62r5yz7RvAJcY',
    appId: '1:847779040961:ios:8e46a8535a9dd741f94e40',
    messagingSenderId: '847779040961',
    projectId: 'mealanalyzer-6c367',
    storageBucket: 'mealanalyzer-6c367.firebasestorage.app',
    iosBundleId: 'com.example.mealAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbOhuAr_ZBnkuTbNAUFirvRQVPqWYh2qQ',
    appId: '1:847779040961:web:a6f35921e0db55caf94e40',
    messagingSenderId: '847779040961',
    projectId: 'mealanalyzer-6c367',
    authDomain: 'mealanalyzer-6c367.firebaseapp.com',
    storageBucket: 'mealanalyzer-6c367.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbOhuAr_ZBnkuTbNAUFirvRQVPqWYh2qQ',
    appId: '1:847779040961:web:a6f35921e0db55caf94e40',
    messagingSenderId: '847779040961',
    projectId: 'mealanalyzer-6c367',
    authDomain: 'mealanalyzer-6c367.firebaseapp.com',
    storageBucket: 'mealanalyzer-6c367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-BXgeYMyKW6OTiuU4nc62r5yz7RvAJcY',
    appId: '1:847779040961:ios:8e46a8535a9dd741f94e40',
    messagingSenderId: '847779040961',
    projectId: 'mealanalyzer-6c367',
    storageBucket: 'mealanalyzer-6c367.firebasestorage.app',
    iosBundleId: 'com.example.mealAnalyzer',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmbisAimbIbJZz2POtNUsMQLy3gM3hgpg',
    appId: '1:847779040961:android:469d191ce0edfac1f94e40',
    messagingSenderId: '847779040961',
    projectId: 'mealanalyzer-6c367',
    storageBucket: 'mealanalyzer-6c367.firebasestorage.app',
  );

}