import 'package:hive_flutter/hive_flutter.dart';
import '../models/meal_result.dart';
import '../../core/constants.dart';

/// Handles all Hive initialisation.
/// Call [HiveService.init] once inside main() before runApp().
class HiveService {
  HiveService._(); // prevent instantiation

  static Future<void> init() async {
    // 1. Init Hive with the Flutter documents directory
    await Hive.initFlutter();

    // 2. Register the generated TypeAdapter for MealResult
    //    (generated by build_runner from meal_result.dart)
    Hive.registerAdapter(MealResultAdapter());

    // 3. Open the box — it stays open for the app lifetime
    await Hive.openBox<MealResult>(AppConstants.mealHistoryBox);
  }
}